### ISSUE TITLE
Cannot upload images

### ISSUE THREAD

**Issue by fl0wfr** [linuxserver/docker-chevereto#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
No error when uploading images

## Current Behavior
When I upload images, I get a red cross on the uploaded pictures with this error message: "Something went wrong: ⚠ errorId #ec7ef5d7f8e14849". I've checked that /data has the correct permissions (1000:1000).

## Steps to Reproduce
1. Simply upload picture. I'm using persistent storage for /data, /config and /app/chevereto

## Environment
**OS:** Rocky Linux 8.6
**CPU architecture:** x86_64
**How docker service was installed:** Official Docker repository

## Command used to create docker container (run/create/compose/screenshot)
`docker run --name "chevereto" --volume "/data/chevereto/config:/config" --volume "/data/chevereto/app:/app/chevereto" --volume "/data/chevereto/data:/data" --restart "unless-stopped" --env "PUID=1000"  --env "PGID=1000" --env "TZ=Europe/Paris" --detach "docker.io/linuxserver/chevereto:latest"`

## Docker logs
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.`
`[s6-init] ensuring user provided files have correct perms...exited 0.`
`[fix-attrs.d] applying ownership & permissions fixes...`
`[fix-attrs.d] done.`
`[cont-init.d] executing container initialization scripts...`
`[cont-init.d] 01-envfile: executing... `
`[cont-init.d] 01-envfile: exited 0.`
`[cont-init.d] 02-tamper-check: executing... `
`[cont-init.d] 02-tamper-check: exited 0.`
`[cont-init.d] 10-adduser: executing... `
`User uid:    1000`
`User gid:    1000`
`[cont-init.d] 10-adduser: exited 0.`
`[cont-init.d] 20-config: executing... `
`[cont-init.d] 20-config: exited 0.`
`[cont-init.d] 30-keygen: executing... `
`using keys found in /config/keys`
`[cont-init.d] 30-keygen: exited 0.`
`[cont-init.d] 50-config: executing... `
`[cont-init.d] 50-config: exited 0.`
`[cont-init.d] 90-custom-folders: executing... `
`[cont-init.d] 90-custom-folders: exited 0.`
`[cont-init.d] 99-custom-files: executing... `
`[custom-init] no custom files found exiting...`
`[cont-init.d] 99-custom-files: exited 0.`
`[cont-init.d] done.`
`[services.d] starting services`
`[services.d] done.`

**Comment by j0nnymoe** [comment]
Unfortunately this won't be looked into as we're dropping this container: https://info.linuxserver.io/issues/2022-06-05-chevereto/ https://github.com/linuxserver/docker-chevereto/pull/17

**Comment by fl0wfr** [comment]
Found, it was related to the use of the paid version, which needs php-dom installed.
